apiVersion: batch/v1
kind: CronJob
metadata:
  name: pdf-comparison-job
  namespace: default
spec:
  schedule: "*/5 * * * *" # Ejecutar cada 5 minutos (para pruebas)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pdf-comparator
            # IMPORTANTE: Cambia 'tu_usuario_dockerhub' por tu usuario real de Docker Hub
            image: jeffdeck/pdf-compare-app:latest 
            imagePullPolicy: Always
            command: ["python", "compare_pdfs.py", "DocumentoA_1.pdf", "DocumentoA2.pdf"]
            env:
            # SDK Key de LaunchDarkly (tomada de tu ejemplo)
            - name: LD_SDK_KEY
              value: "sdk-35c49438-74f2-4f95-be35-7f3a0722d3ae"
            
            # Configuración de Correo Electrónico
            - name: EMAIL_HOST
              value: "smtp.gmail.com"
            - name: EMAIL_PORT
              value: "587"
            - name: EMAIL_HOST_USER
              value: "je1400r@gmail.com"
            - name: EMAIL_HOST_PASSWORD
              value: "qvft zagh ranv askk"
            - name: RECIPIENT_EMAIL
              value: "juanjominino@gmail.com"
              
          restartPolicy: OnFailure