apiVersion: v1
kind: Secret
metadata:
  name: pdf-compare-secrets
  namespace: pdf-compare
  labels:
    app: pdf-compare
type: Opaque
stringData:
  EMAIL_HOST_USER: "je1400r@gmail.com"
  EMAIL_HOST_PASSWORD: "rujh knft pxhc nedf"
  RECIPIENT_EMAIL: "juanjominino@gmail.com"
  LD_SDK_KEY: "sdk-4c9a5f90-1222-4563-8263-4de07217f1a4"
