apiVersion: v1
kind: Service
metadata:
  name: pdf-compare-service
  namespace: pdf-compare
  labels:
    app: pdf-compare
spec:
  type: NodePort
  selector:
    app: pdf-compare
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30080
